# Generated by Django 5.2.6 on 2025-09-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studentprofile_halaqa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='halaqa',
            field=models.CharField(blank=True, choices=[('حلقة البقرة – الشيخ عبد الله الحربي', 'حلقة البقرة – الشيخ عبد الله الحربي'), ('حلقة النساء – الشيخ محمد القحطاني', 'حلقة النساء – الشيخ محمد القحطاني'), ('حلقة التوبة – الشيخ خالد الغامدي', 'حلقة التوبة – الشيخ خالد الغامدي'), ('حلقة النحل – الشيخ فهد العتيبي', 'حلقة النحل – الشيخ فهد العتيبي'), ('حلقة الإسراء – الشيخ محمود الأنصاري', 'حلقة الإسراء – الشيخ محمود الأنصاري'), ('حلقة طه – الشيخ علي الزهراني', 'حلقة طه – الشيخ علي الزهراني'), ('حلقة النمل – الشيخ ياسر البكري', 'حلقة النمل – الشيخ ياسر البكري'), ('حلقة العنكبوت – الشيخ عبد الرحمن الزهراني', 'حلقة العنكبوت – الشيخ عبد الرحمن الزهراني'), ('حلقة لقمان – الشيخ إبراهيم السبيعي', 'حلقة لقمان – الشيخ إبراهيم السبيعي'), ('حلقة فاطر – الشيخ عمر الحربي', 'حلقة فاطر – الشيخ عمر الحربي')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
